### ISSUE TITLE
When querying for a vertex with FETCH_HINT.NONE, accumulo graph doesn't return the vertex, but sql graph does

### ISSUE THREAD

**Issue by sfeng88** [visallo/vertexium#135]

**Comment by mwizeman** [comment]
I added a test to verify the issue. [It fails on this line](https://github.com/visallo/vertexium/blob/135-query-with-fetchhint-none/test/src/main/java/org/vertexium/test/GraphTestBase.java#L1870).

The issue is that the query results iterable rechecks the `has` containers as it [iterates over the results here](https://github.com/visallo/vertexium/blob/master/core/src/main/java/org/vertexium/query/DefaultGraphQueryIterable.java#L100).

In the SQL case, it works because the properties are present even though FetchHint.NONE was given.

In the Accumulo case, it doesn't match anything since we didn't load the properties with the vertices.

Side note: The problem would have surfaced itself with an exception if #131 was in place, which I think would be better.
