### ISSUE TITLE
Performance with mid-size dataset

### ISSUE THREAD

**Issue by snoami** [visallo/vertexium#304]
I have about 90K vertices of specific kind, which correlates to about 4M rows in Accumulo, and it takes about 10 sec to get the full list of vertices. Most of the time is spent in getting the data from Accumulo,  however I have tried it on different configuration with very strong machines on AWS and the performance does not get better than about 10s.  Is that reasonable?  does anyone have experience with such queries? 
Using:
 Vertexium 4.4 with suggested ES / Accumulo / Hadoop
4vCPU, 16GB RAM (AWS m5d.xlarge), 5 servers running Accumulo tservers and Hadoop data nodes, one name node running Accumulo master.

**Comment by joeferner** [comment]
Are you just storing vertices? If not how many edges?
10 seconds to insert? If so how are you inserting the vertices?
10 seconds to query? If so how are you doing the query?
How many properties per vertex?

**Comment by snoami** [comment]
10 sec to query. Not looking at the insert at this point.  I do have edges to almost all vertices. About 5-10 properties per vertex. 
Getting all vertices was just a test.  The real problem is slow performance on queries like:

g.V()
.has("Type", "Actor").has("ActorName",James")
.outE("Acted").inV().outE("HasActor").inV()
has("Type", "Actor").has("Name", "Roby").map

I know the query is a bit redundant but its just an example of graph walk which takes 90 sec! The issue might be that it produces many thousands of scans from Vertexium to accumulo  although there are only 4 actors named James and the end result is 1 item.

**Comment by joeferner** [comment]
Just curious how are you using gremlin queries to query Vertexium? We used to have support for Gremlin but has since been removed because of performance issues. The problem with Gremlin was calling `g.V()...` would end up getting all the vertices sometimes depending on the queries that came after. We couldn't really optimize this since Gremlin was really just executing Groovy code which we had little to no control over.

We have since added Cypher query support but it too has some performance impacts depending on how you structure your query (putting filters in the WHERE clause vs the primary vertex clause for example). The nice thing about Cypher though is we have complete control over how the query executes so optimizations can be made.

But for the best and most consistent performance you are better off writing direct Vertexium code and be sure to bundle up as many ids as possible per query.

Some pseudo code
```
actorVertices = g.query().has("Type","Actor").has("ActorName","James").vertices(FetchHints.OUT_EDGE_REFS)
connectedActorVertexIds = stream(actorVertices).flatMap(v->v.getVertexIds(IN))
connectedActorVertices = g.getVertices(connectedActorVertexIds)
...
```
So instead of for each actor vertex named James calling recursively getting his connected vertices. You would batch up each stage all connected vertex ids and call Vertexium once to get all connected.

**Comment by snoami** [comment]
Indeed I was using Gremlin and when I wrote it directly the performance was much better. thank you!

**Comment by snoami** [comment]
After a few tests indeed the direct approach works must faster than Gremlin but I find it very complicated to do "path", which is of course simple in Gremlin. When using  "getVertices(Ids)" I get all the connections of those Ids, and I cannot know which Id leads to which. If I do it one by one I loss the efficiency which was the starting point of this topic. 
Is there a way to get the path via the Vertexium API?

**Comment by joeferner** [comment]
Unfortunately no not right now.  Cypher will be the answer in the future as performance and optimizations to Cypher take place, but right now code is your best bet.
